/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddBook: typeof import('./src/components/Modals/AddBook.vue')['default']
    AddCategory: typeof import('./src/components/Modals/AddCategory.vue')['default']
    BookList: typeof import('./src/components/BookList.vue')['default']
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
    copy: typeof import('./src/components/Modals/EditCategory copy.vue')['default']
    DeleteBook: typeof import('./src/components/Modals/DeleteBook.vue')['default']
    DeleteCategory: typeof import('./src/components/Modals/DeleteCategory.vue')['default']
    EditBook: typeof import('./src/components/Modals/EditBook.vue')['default']
    EditCategory: typeof import('./src/components/Modals/EditCategory.vue')['default']
    FilterBook: typeof import('./src/components/Dropdowns/FilterBook.vue')['default']
    ImageBook: typeof import('./src/components/Modals/ImageBook.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
